In [1]:
import numpy as np

In [19]:
#Create a null vector of size 10
V =np.zeros(10)
print (V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#Create a null vector of size 10 but the fifth value which is 1
V =np.zeros(10)
V[4] =1
print (V)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
Create a vector with values ranging from 10 to 49
V =np.arange(10,50)
print (V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
#Reverse a vector (the first element becomes last)
V =np.arange(50)[::-1]
print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [26]:
#Create a 3x3 matrix with values ranging from 0 to 8
V =np.arange(9).reshape(3,3)
print(V)
np.shape(V)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(3, 3)

In [27]:
#Find indices of non­zero elements from [1,2,0,0,4,0] - means position within the array
nonzero =np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4], dtype=int64),)


In [29]:
#Create a 3x3x3 array with random values
V =np.random.random((3,3,3))
print(V)

[[[0.42412272 0.27100199 0.3423806 ]
  [0.62602084 0.95552865 0.14723566]
  [0.63540481 0.03052999 0.64938123]]

 [[0.2071242  0.38138535 0.66709621]
  [0.4301848  0.64312055 0.19304031]
  [0.03170032 0.50740503 0.88213713]]

 [[0.89270535 0.38574072 0.44179223]
  [0.61163474 0.0817963  0.67580331]
  [0.0205643  0.37480791 0.49502289]]]


In [30]:
#Create a random vector of size 30 and find the mean value
V =np.random.random(30)
mean =V.mean()
print(mean)

0.5673968016204647


In [33]:
#Create a 2d array with 1 on the border and 0 inside (data element is referred by two indices instead of one)
V =np.ones((9,9))
V[1:-1,1:-1] =0
print(V)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
#Create an 8x8 matrix and fill it with a checkerboard pattern
V =np.zeros((8,8),dtype=int)
V[1::2,::2] =1 #Slice from 1st index row till 1+2+2… and fill all columns with 1 starting from 0th to 0+2+2… and so on.
V[::2,1::2] =1 #Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2+…..
print(V)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
#What is the major difference between sets, lists, tuples, and dictionaries?
#Answer - Lists and tuples are ordered collection of items, sets and dictionaries are not. Items in lists can be replaced 
#or changed but not in the others. Dictionaries are the only one of the 4 which hold pairs of values
#Lists and sets are mutable, the other are immutable

In [38]:
#Print first 10 natural numbers using while loop
i = 1
while(i<=10):
    print(i)
    i += 1 #x(i)  = x(i) + y(1)

1
2
3
4
5
6
7
8
9
10


In [82]:
#Print the numbers -10 to -1 using for loop.
V =np.negative(np.arange(1,11)[::-1])
for i in V:
    print (i)
    
print("or")

for V in range(-10,0):
    print (V)


-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
or
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [95]:
#Print the message “Done” after successful execution of any for loop.
V =np.negative(np.arange(1,11)[::-1])
for i in V:
    print ("done :%s" %i)

done :-10
done :-9
done :-8
done :-7
done :-6
done :-5
done :-4
done :-3
done :-2
done :-1


In [96]:
#Create a random vector of size 10 and sort it
v = np.random.random(10)
print("Original array:")
print(v)
v.sort()
print("Sorted array:")
print(v)

Original array:
[0.33070427 0.80647244 0.79150037 0.46285249 0.90894478 0.86101377
 0.61604109 0.01670795 0.32071825 0.14643338]
Sorted array:
[0.01670795 0.14643338 0.32071825 0.33070427 0.46285249 0.61604109
 0.79150037 0.80647244 0.86101377 0.90894478]


In [78]:
#Execute any three math functions using numpy.
print("first function")
print(np.log10(4))
a=np.random.random(10)
b=np.random.random(10)
print("second function")
print(np.add(a,b))
print("third function")
c=np.random.random(10)
d=np.random.random(10)
print(np.power(a,b))


first function
0.6020599913279624
second function
[0.97819271 1.28160435 0.69066619 0.66985593 0.67267453 0.96368762
 1.52849601 0.10713076 0.74066641 1.24483925]
third function
[0.67510318 0.99550452 0.6741788  0.73409128 0.87418144 0.39342336
 0.94211512 0.87020215 0.00809271 0.61666766]
